name: Truls Aagedal
favicon: null
layout_spectrum: 0.01362
typography_spectrum: 1
title: – directing the world towards the future –
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#272727'
    - '#ab0000'
    - '#3e3e3e'
    - '#616161'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
